id: I05B97B8F
legacy_id: P001724
ocr_import_info:
  bdrc_scan_id: W1CZ2857
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:31:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:29:54.192776+00:00'
last_modified: 2022-08-31 03:33:29.985198
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2857
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2857
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དགེ་འདུན་རྒྱ་མཚོ།
  author: ཏཱ་ལའི་བླ་མ ༠༢་དགེ་འདུན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9560579858167509
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1CZ2871:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2871
      total_pages: 414
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1CZ2871.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9421763016822509
    legacy_id: v005
  I1CZ2869:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2869
      total_pages: 536
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1CZ2869.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9544366142822953
    legacy_id: v003
  I1CZ2868:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2868
      total_pages: 602
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1CZ2868.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9512424373154339
    legacy_id: v002
  I1CZ2870:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2870
      total_pages: 562
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1CZ2870.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9613800193089262
    legacy_id: v004
  I1CZ2872:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2872
      total_pages: 512
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1CZ2872.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9587028184039394
    legacy_id: v006
  I1CZ2867:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2867
      total_pages: 442
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2867.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9649886083887992
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
