id: I05B97B8F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:35:05+00:00'
last_modified: '2022-06-07T14:12:46.572800+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2857
  title: གསུང་འབུམ། དགེ་འདུན་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B050:
      image_group_id: I1CZ2867
      title: ''
      total_pages: 442
      order: 1
      base_file: B050.txt
    '9744':
      image_group_id: I1CZ2868
      title: ''
      total_pages: 602
      order: 2
      base_file: 9744.txt
    '6778':
      image_group_id: I1CZ2869
      title: ''
      total_pages: 536
      order: 3
      base_file: 6778.txt
    8CDA:
      image_group_id: I1CZ2870
      title: ''
      total_pages: 562
      order: 4
      base_file: 8CDA.txt
    38FC:
      image_group_id: I1CZ2871
      title: ''
      total_pages: 414
      order: 5
      base_file: 38FC.txt
    '9779':
      image_group_id: I1CZ2872
      title: ''
      total_pages: 512
      order: 6
      base_file: 9779.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
